http://127.0.0.1:5000/getProducts

### 
http://127.0.0.1:5000/getProductByName?productName=Tortillas

### 
http://127.0.0.1:5000/getProductByID?id=25


### 
POST http://127.0.0.1:5000/addProduct
Content-Type: application/json

{
  "name": "Spaguetti", 
  "brand": "Casero", 
  "variation": "Boloñesa", 
  "price": 0
}